import { BiomeType } from '../biomes/types'

export type SpeciesId = 'deer' | 'rabbit' | 'bird' | 'dragon' | 'fish' | 'wolf' | 'croc'
  | 'bear' | 'camel' | 'fox' | 'bat' | 'scorpion' | 'lion' | 'mammoth' | 'toad'
  | 'titan' | 'skywhale' | 'wurm' | 'imp' | 'hellhound' | 'infernal'
  | 'eagle' | 'parrot' | 'crab' | 'goat'

export interface SpeciesDef {
  id: SpeciesId
  mobility: 'ground' | 'air' | 'water'
  role: 'herbivore' | 'predator'
  bodyColor: number
  headColor: number
  legColor: number
  bodyW: number
  bodyH: number
  bodyD: number
  maxSpeed: number
  fleeSpeed: number
  maxHunger: number
  maxThirst: number
  maxEnergy: number
  maxAge: number
  sightRange: number
  attackRange: number
  attackDamage: number
  preferredBiomes: BiomeType[]
  spawnWeight: number
  adultScale: number
  babyScale: number
  isGiant?: boolean    // building-sized creatures, extremely rare
}

export const SPECIES: Record<SpeciesId, SpeciesDef> = {
  rabbit: {
    id: 'rabbit',
    mobility: 'ground',
    role: 'herbivore',
    bodyColor: 0xc8a878,
    headColor: 0xd4b488,
    legColor: 0xb89868,
    bodyW: 0.4, bodyH: 0.3, bodyD: 0.6,
    maxSpeed: 6,
    fleeSpeed: 10,
    maxHunger: 180,
    maxThirst: 120,
    maxEnergy: 100,
    maxAge: 300,
    sightRange: 6,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Forest, BiomeType.Savanna, BiomeType.Tundra],
    spawnWeight: 3,
    adultScale: 0.7,
    babyScale: 0.35,
  },

  deer: {
    id: 'deer',
    mobility: 'ground',
    role: 'herbivore',
    bodyColor: 0x8b6914,
    headColor: 0x9a7820,
    legColor: 0x7a5a10,
    bodyW: 0.7, bodyH: 0.6, bodyD: 1.2,
    maxSpeed: 5,
    fleeSpeed: 10,
    maxHunger: 240,
    maxThirst: 180,
    maxEnergy: 100,
    maxAge: 600,
    sightRange: 10,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Forest, BiomeType.Savanna, BiomeType.Swamp],
    spawnWeight: 2,
    adultScale: 1.0,
    babyScale: 0.5,
  },

  bird: {
    id: 'bird',
    mobility: 'air',
    role: 'herbivore',
    bodyColor: 0x4488cc,
    headColor: 0x3366aa,
    legColor: 0x996600,
    bodyW: 0.3, bodyH: 0.25, bodyD: 0.5,
    maxSpeed: 8,
    fleeSpeed: 14,
    maxHunger: 120,
    maxThirst: 90,
    maxEnergy: 100,
    maxAge: 240,
    sightRange: 14,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [
      BiomeType.Forest, BiomeType.Desert, BiomeType.Volcanic, BiomeType.Snow,
      BiomeType.Swamp, BiomeType.Tundra, BiomeType.Mushroom, BiomeType.AshWastes,
      BiomeType.Crystal, BiomeType.Savanna,
    ],
    spawnWeight: 3,
    adultScale: 0.8,
    babyScale: 0.4,
  },

  dragon: {
    id: 'dragon',
    mobility: 'air',
    role: 'predator',
    bodyColor: 0x882200,
    headColor: 0x661100,
    legColor: 0x441100,
    bodyW: 1.2, bodyH: 0.8, bodyD: 2.4,
    maxSpeed: 7,
    fleeSpeed: 7,
    maxHunger: 300,
    maxThirst: 300,
    maxEnergy: 100,
    maxAge: 1200,
    sightRange: 35,
    attackRange: 4,
    attackDamage: 20,
    preferredBiomes: [BiomeType.Volcanic, BiomeType.AshWastes, BiomeType.Crystal],
    spawnWeight: 1,
    adultScale: 1.4,
    babyScale: 0.6,
  },

  fish: {
    id: 'fish',
    mobility: 'water',
    role: 'herbivore',
    bodyColor: 0x22aacc,
    headColor: 0x1188aa,
    legColor: 0x115566,
    bodyW: 0.35, bodyH: 0.2, bodyD: 0.7,
    maxSpeed: 4,
    fleeSpeed: 7,
    maxHunger: 180,
    maxThirst: 0,
    maxEnergy: 100,
    maxAge: 360,
    sightRange: 6,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Swamp, BiomeType.Forest, BiomeType.Savanna, BiomeType.Tundra, BiomeType.Snow],
    spawnWeight: 2,
    adultScale: 1.0,
    babyScale: 0.5,
  },

  wolf: {
    id: 'wolf',
    mobility: 'ground',
    role: 'predator',
    bodyColor: 0x556677,
    headColor: 0x445566,
    legColor: 0x334455,
    bodyW: 0.65, bodyH: 0.55, bodyD: 1.1,
    maxSpeed: 6,
    fleeSpeed: 6,
    maxHunger: 360,
    maxThirst: 240,
    maxEnergy: 100,
    maxAge: 720,
    sightRange: 18,
    attackRange: 2,
    attackDamage: 15,
    preferredBiomes: [BiomeType.Forest, BiomeType.Tundra],
    spawnWeight: 1,
    adultScale: 1.0,
    babyScale: 0.5,
  },

  croc: {
    id: 'croc',
    mobility: 'water',
    role: 'predator',
    bodyColor: 0x3a5c28,
    headColor: 0x2e4a1e,
    legColor: 0x4a6e35,
    bodyW: 0.9,
    bodyH: 0.28,
    bodyD: 2.2,
    maxSpeed: 3,
    fleeSpeed: 5,
    maxHunger: 180,
    maxThirst: 0,
    maxEnergy: 100,
    maxAge: 300,
    sightRange: 18,
    attackRange: 2.5,
    attackDamage: 18,
    preferredBiomes: [BiomeType.Swamp, BiomeType.Forest],
    spawnWeight: 1,
    adultScale: 1.1,
    babyScale: 0.55,
  },

  bear: {
    id: 'bear',
    mobility: 'ground',
    role: 'predator',
    bodyColor: 0x6b4423,
    headColor: 0x7a5230,
    legColor: 0x5a3318,
    bodyW: 1.2, bodyH: 0.9, bodyD: 1.8,
    maxSpeed: 5,
    fleeSpeed: 8,
    maxHunger: 420,
    maxThirst: 300,
    maxEnergy: 100,
    maxAge: 900,
    sightRange: 16,
    attackRange: 2.5,
    attackDamage: 25,
    preferredBiomes: [BiomeType.Forest, BiomeType.Snow, BiomeType.Tundra],
    spawnWeight: 1,
    adultScale: 1.1,
    babyScale: 0.5,
  },

  camel: {
    id: 'camel',
    mobility: 'ground',
    role: 'herbivore',
    bodyColor: 0xd4a866,
    headColor: 0xe0bc78,
    legColor: 0xb89050,
    bodyW: 0.9, bodyH: 1.0, bodyD: 1.8,
    maxSpeed: 6,
    fleeSpeed: 9,
    maxHunger: 360,
    maxThirst: 60,
    maxEnergy: 100,
    maxAge: 720,
    sightRange: 10,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Desert],
    spawnWeight: 2,
    adultScale: 1.1,
    babyScale: 0.5,
  },

  fox: {
    id: 'fox',
    mobility: 'ground',
    role: 'predator',
    bodyColor: 0xd44d11,
    headColor: 0xe05520,
    legColor: 0xaa3308,
    bodyW: 0.45, bodyH: 0.4, bodyD: 0.9,
    maxSpeed: 9,
    fleeSpeed: 9,
    maxHunger: 300,
    maxThirst: 180,
    maxEnergy: 100,
    maxAge: 480,
    sightRange: 14,
    attackRange: 1.5,
    attackDamage: 8,
    preferredBiomes: [BiomeType.Forest, BiomeType.Snow, BiomeType.Savanna],
    spawnWeight: 1,
    adultScale: 0.9,
    babyScale: 0.4,
  },

  bat: {
    id: 'bat',
    mobility: 'air',
    role: 'predator',
    bodyColor: 0x2a1a3a,
    headColor: 0x1a0a2a,
    legColor: 0x221230,
    bodyW: 0.4, bodyH: 0.25, bodyD: 0.5,
    maxSpeed: 9,
    fleeSpeed: 9,
    maxHunger: 240,
    maxThirst: 120,
    maxEnergy: 100,
    maxAge: 360,
    sightRange: 20,
    attackRange: 1.5,
    attackDamage: 5,
    preferredBiomes: [BiomeType.Volcanic, BiomeType.AshWastes, BiomeType.Mushroom],
    spawnWeight: 1,
    adultScale: 0.9,
    babyScale: 0.4,
  },

  scorpion: {
    id: 'scorpion',
    mobility: 'ground',
    role: 'predator',
    bodyColor: 0x8b3a0a,
    headColor: 0x9e4a12,
    legColor: 0x6e2a06,
    bodyW: 0.5, bodyH: 0.25, bodyD: 0.8,
    maxSpeed: 4,
    fleeSpeed: 6,
    maxHunger: 240,
    maxThirst: 60,
    maxEnergy: 100,
    maxAge: 480,
    sightRange: 8,
    attackRange: 2,
    attackDamage: 15,
    preferredBiomes: [BiomeType.Desert],
    spawnWeight: 1,
    adultScale: 0.9,
    babyScale: 0.45,
  },

  lion: {
    id: 'lion',
    mobility: 'ground',
    role: 'predator',
    bodyColor: 0xd4a832,
    headColor: 0xc89628,
    legColor: 0xa87820,
    bodyW: 0.9, bodyH: 0.7, bodyD: 1.6,
    maxSpeed: 7,
    fleeSpeed: 7,
    maxHunger: 360,
    maxThirst: 240,
    maxEnergy: 100,
    maxAge: 720,
    sightRange: 20,
    attackRange: 2.5,
    attackDamage: 18,
    preferredBiomes: [BiomeType.Savanna],
    spawnWeight: 1,
    adultScale: 1.1,
    babyScale: 0.5,
  },

  mammoth: {
    id: 'mammoth',
    mobility: 'ground',
    role: 'herbivore',
    bodyColor: 0x7a6858,
    headColor: 0x8a7868,
    legColor: 0x6a5848,
    bodyW: 1.4, bodyH: 1.2, bodyD: 2.4,
    maxSpeed: 4,
    fleeSpeed: 6,
    maxHunger: 480,
    maxThirst: 360,
    maxEnergy: 100,
    maxAge: 1800,
    sightRange: 12,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Snow, BiomeType.Tundra],
    spawnWeight: 1,
    adultScale: 1.3,
    babyScale: 0.6,
  },

  toad: {
    id: 'toad',
    mobility: 'ground',
    role: 'herbivore',
    bodyColor: 0x4a6e28,
    headColor: 0x5a7e32,
    legColor: 0x3a5e1e,
    bodyW: 0.5, bodyH: 0.3, bodyD: 0.6,
    maxSpeed: 3,
    fleeSpeed: 5,
    maxHunger: 120,
    maxThirst: 240,
    maxEnergy: 100,
    maxAge: 240,
    sightRange: 6,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Swamp, BiomeType.Mushroom, BiomeType.Forest],
    spawnWeight: 2,
    adultScale: 0.8,
    babyScale: 0.4,
  },

  // ── Giants — building-sized, extremely rare ─────────────────────────────

  titan: {
    id: 'titan',
    mobility: 'ground',
    role: 'herbivore',
    isGiant: true,
    bodyColor: 0x6a6a70,
    headColor: 0x7a7a80,
    legColor: 0x5a5a60,
    bodyW: 5, bodyH: 4, bodyD: 7,
    maxSpeed: 1.2,
    fleeSpeed: 1.8,
    maxHunger: 9999,
    maxThirst: 9999,
    maxEnergy: 200,
    maxAge: 99999,
    sightRange: 30,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Forest, BiomeType.Snow, BiomeType.Tundra, BiomeType.Savanna, BiomeType.Swamp],
    spawnWeight: 1,
    adultScale: 12,
    babyScale: 6,
  },

  skywhale: {
    id: 'skywhale',
    mobility: 'air',
    role: 'herbivore',
    isGiant: true,
    bodyColor: 0x4466aa,
    headColor: 0x5577bb,
    legColor: 0x3355aa,
    bodyW: 6, bodyH: 3.5, bodyD: 10,
    maxSpeed: 1.5,
    fleeSpeed: 2,
    maxHunger: 9999,
    maxThirst: 9999,
    maxEnergy: 200,
    maxAge: 99999,
    sightRange: 40,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [
      BiomeType.Forest, BiomeType.Desert, BiomeType.Snow, BiomeType.Tundra,
      BiomeType.Savanna, BiomeType.Crystal, BiomeType.Heaven,
    ],
    spawnWeight: 1,
    adultScale: 10,
    babyScale: 5,
  },

  wurm: {
    id: 'wurm',
    mobility: 'ground',
    role: 'herbivore',
    isGiant: true,
    bodyColor: 0x8a4420,
    headColor: 0x9a5430,
    legColor: 0x7a3410,
    bodyW: 3, bodyH: 3, bodyD: 12,
    maxSpeed: 1.0,
    fleeSpeed: 1.5,
    maxHunger: 9999,
    maxThirst: 9999,
    maxEnergy: 200,
    maxAge: 99999,
    sightRange: 20,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Desert, BiomeType.Volcanic, BiomeType.AshWastes, BiomeType.Mushroom],
    spawnWeight: 1,
    adultScale: 10,
    babyScale: 5,
  },

  imp: {
    id: 'imp',
    mobility: 'air',
    role: 'predator',
    bodyColor: 0xaa2200,
    headColor: 0x881100,
    legColor: 0x661100,
    bodyW: 0.35, bodyH: 0.3, bodyD: 0.5,
    maxSpeed: 10,
    fleeSpeed: 10,
    maxHunger: 200,
    maxThirst: 120,
    maxEnergy: 100,
    maxAge: 300,
    sightRange: 16,
    attackRange: 1.5,
    attackDamage: 8,
    preferredBiomes: [BiomeType.Hell],
    spawnWeight: 3,
    adultScale: 0.9,
    babyScale: 0.4,
  },

  hellhound: {
    id: 'hellhound',
    mobility: 'ground',
    role: 'predator',
    bodyColor: 0x331100,
    headColor: 0x441100,
    legColor: 0x220800,
    bodyW: 0.7, bodyH: 0.6, bodyD: 1.2,
    maxSpeed: 8,
    fleeSpeed: 8,
    maxHunger: 360,
    maxThirst: 240,
    maxEnergy: 100,
    maxAge: 720,
    sightRange: 20,
    attackRange: 2.5,
    attackDamage: 20,
    preferredBiomes: [BiomeType.Hell, BiomeType.Volcanic],
    spawnWeight: 2,
    adultScale: 1.1,
    babyScale: 0.5,
  },

  infernal: {
    id: 'infernal',
    mobility: 'ground',
    role: 'herbivore',
    isGiant: true,
    bodyColor: 0x441100,
    headColor: 0x551500,
    legColor: 0x330800,
    bodyW: 5, bodyH: 4.5, bodyD: 7,
    maxSpeed: 1.2,
    fleeSpeed: 1.8,
    maxHunger: 9999,
    maxThirst: 9999,
    maxEnergy: 200,
    maxAge: 99999,
    sightRange: 30,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Hell],
    spawnWeight: 1,
    adultScale: 12,
    babyScale: 6,
  },

  eagle: {
    id: 'eagle',
    mobility: 'air',
    role: 'predator',
    bodyColor: 0x5a3a1a,
    headColor: 0xf0f0e8,
    legColor: 0xccaa00,
    bodyW: 0.5, bodyH: 0.4, bodyD: 0.8,
    maxSpeed: 12,
    fleeSpeed: 12,
    maxHunger: 300,
    maxThirst: 180,
    maxEnergy: 100,
    maxAge: 600,
    sightRange: 30,
    attackRange: 2,
    attackDamage: 12,
    preferredBiomes: [BiomeType.Alpine, BiomeType.Cliffs, BiomeType.FloatingIslands, BiomeType.Mesa],
    spawnWeight: 2,
    adultScale: 1.0,
    babyScale: 0.5,
  },

  parrot: {
    id: 'parrot',
    mobility: 'air',
    role: 'herbivore',
    bodyColor: 0x22cc44,
    headColor: 0xff4444,
    legColor: 0x666666,
    bodyW: 0.3, bodyH: 0.25, bodyD: 0.4,
    maxSpeed: 7,
    fleeSpeed: 12,
    maxHunger: 120,
    maxThirst: 90,
    maxEnergy: 100,
    maxAge: 360,
    sightRange: 10,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Jungle, BiomeType.Oasis],
    spawnWeight: 3,
    adultScale: 0.7,
    babyScale: 0.35,
  },

  crab: {
    id: 'crab',
    mobility: 'ground',
    role: 'herbivore',
    bodyColor: 0xcc4422,
    headColor: 0xdd5533,
    legColor: 0xaa3311,
    bodyW: 0.4, bodyH: 0.2, bodyD: 0.5,
    maxSpeed: 3,
    fleeSpeed: 5,
    maxHunger: 180,
    maxThirst: 60,
    maxEnergy: 100,
    maxAge: 300,
    sightRange: 5,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.CoralReef, BiomeType.Bog],
    spawnWeight: 2,
    adultScale: 0.8,
    babyScale: 0.4,
  },

  goat: {
    id: 'goat',
    mobility: 'ground',
    role: 'herbivore',
    bodyColor: 0xccccbb,
    headColor: 0xddddcc,
    legColor: 0x888877,
    bodyW: 0.6, bodyH: 0.5, bodyD: 0.9,
    maxSpeed: 6,
    fleeSpeed: 9,
    maxHunger: 240,
    maxThirst: 180,
    maxEnergy: 100,
    maxAge: 480,
    sightRange: 10,
    attackRange: 0,
    attackDamage: 0,
    preferredBiomes: [BiomeType.Alpine, BiomeType.Mesa, BiomeType.Badlands, BiomeType.Taiga],
    spawnWeight: 2,
    adultScale: 1.0,
    babyScale: 0.5,
  },
}

export const ALL_SPECIES: SpeciesId[] = ['deer', 'rabbit', 'bird', 'dragon', 'fish', 'wolf', 'croc', 'bear', 'camel', 'fox', 'bat', 'scorpion', 'lion', 'mammoth', 'toad', 'titan', 'skywhale', 'wurm', 'imp', 'hellhound', 'infernal', 'eagle', 'parrot', 'crab', 'goat']
